### ISSUE TITLE
When using PeriodicalLogger, multiple CollectorThreads may be created

### ISSUE THREAD

**Issue by guss77** [jalkanen/speed4j#1]
The problem is that the CollectorThread is only created "lazily" the first time a StopWatch is submitted for logging. 

But there is no protection from multi-threaded calls, and if the Speed4J user just starts hammering immediately from multiple threads, multiple CollectorThread instances may be created before the m_collectorThread field is actually set, and as a result logging will be broken.

The solution, I think, is to have the collector thread instantiated eagerly in the constructor. Its also probably a good idea to set it as a deamon thread so it won't block an exiting JVM.

**Comment by jalkanen** [comment]
Good catch. Fix forthcoming.

**Comment by guss77** [comment]
Thanks.
