### ISSUE TITLE
Add space between timer and message

### ISSUE THREAD

**Issue by rstml** [jalkanen/speed4j#12]
https://github.com/jalkanen/speed4j/blob/master/src/main/java/com/ecyrd/speed4j/StopWatch.java#L201

there's no spacing between timer and message, should be:

``` java
        return (m_tag != null ? m_tag : DEFAULT_TAG).concat(": ").concat(getReadableTime()).concat(" ").concat( (m_message != null ? m_message : "") );
```

**Comment by jalkanen** [comment]
Good catch, thanks!
