### ISSUE TITLE
Setting the slf4jLogname to an empty string turns off JMX stats

### ISSUE THREAD

**Issue by rstml** [jalkanen/speed4j#13]
According to README

```
Q: I want to see just the JMX data, not the logging.

A: Set the slf4jLogname to an empty string. For example 
   speed4j.loggingFactory.slf4jLogname=
```

However this won't work due to:

https://github.com/jalkanen/speed4j/blob/master/src/main/java/com/ecyrd/speed4j/log/PeriodicalLog.java#L286

**Comment by jalkanen** [comment]
Hmm... Suggestions on how this should work?

**Comment by rstml** [comment]
I'd prefer explicit config option for this, something like PeriodicalLog.setMode() where mode can be FILE_ONLY, JMX_ONLY or ALL.

**Comment by jalkanen** [comment]
Might be best, agreed.

**Comment by rstml** [comment]
Also, I found logging individual events missing in PeriodicalLog (just like Slf4jLog does) and had to extend it. I think this can be one of the modes, e.g.: JMX, FILE_PERIODICAL, FILE_INDIVIDUAL.
