### ISSUE TITLE
Allow clients to change the config file name

### ISSUE THREAD

**Issue by patricioe** [jalkanen/speed4j#15]
I think it would be useful (like log4j works) to allow clients to specify different config files by making the speed4j load the config file based on a system variable.

like:

```
 private static final String SPEED4J_CONFIG_KEY = "speed4j.config";

 if ( ! locationSet() )  {
      System.setProperty(SPEED4J_CONFIG_KEY, DEFAULT_LOCATION);
 }
```

I'll be happy to contribute the patch if it makes sense to you.

the problem we see in Hector (based on an email in the email list) is that users that package their binaries, the speed4j.properties used in Hector gets copied and they end up with 2 versions of speed4j config files in their classpath.

**Comment by jalkanen** [comment]
Good idea, will gladly accept a patch.
