### ISSUE TITLE
speed4j.<loggingFactory>.period should be modifiable via JMX

### ISSUE THREAD

**Issue by fruxo-** [jalkanen/speed4j#16]
For what I've been able to see, currently it is not possible to dynamically change a logger's period.
However it would be really useful if this was possible since in many cases it is not possible to simply shut down and restart all of your nodes to simply change the period used to log the stats.

Similarly, the options JMX_ONLY, LOG_ONLY, QUITE, are good candidates to be dynamically set via JMX.

**Comment by jalkanen** [comment]
Sure, why not. I'll try to squeeze in some time to do this!

**Comment by fruxo-** [comment]
Thanks.
