### ISSUE TITLE
CollectedStatistics are kept in memory longer then needed

### ISSUE THREAD

**Issue by guss77** [jalkanen/speed4j#3]
The PeriodicalLog creates a new CollectedStatistics collection object for each doLog() run, and then keeps it as an object member (including huge lists of statistics) until the next time doLog() is run, when the retained object is simply discarded.

When using long log periods and with a lot of traffic, the CollectedStatistics collection object can grow to many megabytes, and is then kept in memory for a long period even though it is never used.

Its probably a better idea to use a local variable for the time localized analysis instead of retaining the temporary results in memory.

**Comment by jalkanen** [comment]
Yup, you're right. It should also cache any requested average/mean/etc numbers for JMX queries (which may occur at any time).

**Comment by guss77** [comment]
I see - now that I look at this again, I can see that the m_statistics member is used in JMX queries - so you do need to keep it overtime. But maybe, knowing the type of information JXM queries have, you can freeze/cache the results of CollectedStatistics and discard the long data queue. 

This is mostly problematic with the getPercentile() query, which CollectedStatistics doesn't know what percentile will be asked, but PeriodicalLog does.

**Comment by jalkanen** [comment]
The good thing is that CollectedStatistics is mostly a private object to PeriodicalLog, so I don't think we need to worry too much about the getPercentile(). Everything can be cached, and PeriodicalLog can maintain an internal list of the percentiles requested.

**Comment by jalkanen** [comment]
Trunk has now a fix candidate, will be in 0.8.

**Comment by guss77** [comment]
Well, the computing twice might be a problem but it would be easy to fix this by adding caching in CollectedStatistics - if it will be needed. At this point I think this is good enough :-) thanks.
