### ISSUE TITLE
Improving StopWatch.toString() performance

### ISSUE THREAD

**Issue by patricioe** [jalkanen/speed4j#4]
Hi Janne, I'm a developer of Hector.

I went through you code here and also Hector core trying to reduce the memory footprint.

I found that  String.concat() results in better performance and more efficient memory usage thant just "aaa" + "bbbb"

This would be my suggestion:

Before:

   public String toString() {
        return (m_tag != null ? m_tag : DEFAULT_TAG)+": "+getReadableTime() + (m_message != null ? m_message : "");
    }

After

```
public String toString()  {
    return (m_tag != null ? m_tag : DEFAULT_TAG).concat(": ").concat(getReadableTime() + (m_message != null ? m_message : ""));
}
```

Also you might want to have:

static final String COLOM = ":";

All of this is not a big of a deal, but for performance stuff it's good that the tools have as little footprint as possible.

Thoughts?

**Comment by patricioe** [comment]
actually in my suggestion there is an extra + that can be replaced with "concat".

**Comment by jalkanen** [comment]
OK, I'll actually have to test this - quick googling suggests that concat() is faster than + when you have 2-3 objects to concatenate; otherwise + wins. Since we've got three or four, I'd like to see the actual numbers first :-)

**Comment by patricioe** [comment]
sure.  I tested with 2 and it was faster and even better I produced less garbage.
the later is the whole point of replacing for concat()

I tested it with Yourkit.

**Comment by patricioe** [comment]
few more lines.

in 10M operations and concatenating 2 strings only, String.concat() took have the time and produced 300k less objects.

This was only in Hector.

Speed4j toString() methods concats more than 2 String. I truly believe that if you make that change, at least in Hector we'll end up saving more than 500k objects creation.

**Comment by jalkanen** [comment]
Well, String concatenation is more complicated than that - the "+" operator can be optimized freely by the compiler to use the fastest route.  Also, doing two concat()s is not necessarily faster than using StringBuilder; or "+". In fact, I ran a few tests and it suggests that with five operations "+" is faster.  So

String foo = a+b+c+d+e;

is faster than

String foo = a.concat(b).concat(c).concat(d).concat(e).

However, with only three operands concat is slightly faster than "+". So foo = a.concat(b).concat(c) is slightly faster than foo = a+b+c.

With four operands, it's about even.  So I think we can make this change.

**Comment by patricioe** [comment]
we you able to mesure the amount of objects created?

**Comment by jalkanen** [comment]
I did take a look using JProfiler, and it didn't seem to differ by that much. Which is only logical, since concat().concat() creates a new String() for every call (i.e. foo = a.concat(b).concat(c) creates two new objects) and  foo = a+b+c also creates two new objects (one StringBuilder and one String()). This also explains why "+" is faster when you append multiple objects, since it still only creates two objects (assuming the StringBuilder buffer is large enough to start with), but concat() creates a new object on every call.

**Comment by jalkanen** [comment]
Obviously, if you only measure two strings, concat() creates only one object, whereas "+" still creates two objects. Hence the savings in object count you were observing.
