### ISSUE TITLE
Memory Leak in PeriodicalLog's StopWatch queue (PNG links of profiler included)

### ISSUE THREAD

**Issue by bmacdonald-rhap** [jalkanen/speed4j#7]
Greetings!

I'm part of the quality assurance team working on a web service using Jersey and Apache Tomcat, written in Java. We use Hector 0.8.0-1 (using hector-core 0.8.0-1 & hector-object-mapper 1.0-07 dependencies in Maven) to access Cassandra clusters, hence the presence of speed4j classes in memory for our service. 

We recently ran a longevity test on our web service in conjunction with the YourKit Profiler, to find any outstanding performance issues. The run lasted approximately 24 hours.

We did find a serious memory leak involving the PeriodicalLog object -- in particular, its StopWatch queue, which had amassed 700MB of retained memory over time.

Our code has no direct access to any speed4j objects. These are created only by our use of the Hector client we imported.

I provided two screenshots of the Profile Snapshot generated from the day-long run below, which includes speed4j classes at the top:
- General Memory panel for retained classes, notably the top 6 (PNG image link): http://tinypic.com/r/11i0okk/7
- Panel with PeriodicalLog Recent Instances, showing giant m_queue linked link (PNG image link): http://tinypic.com/r/b55u37/7

The machine this ran on on had 16GB of memory. The application started with a heap size of 1GB with a max heap size of 1.5GB.

I initially reported this in the hector-users google group. I was quickly led here, which seems a more appropriate place to report the issue.

Looking at the PeriodicalLog code, I see a potential problem...
https://github.com/jalkanen/speed4j/blob/master/src/main/java/com/ecyrd/speed4j/log/PeriodicalLog.java

Its doLog statement will only remove a StopWatch from the queue if the StopWatch's creation time at the end of the queue is older in time than a "finalMoment" time passed to the call itself. There is a comment above the function that warns of "finalMoment" slipping if there are a lot of Threads, and calculations become too slow. But the comment is vague about what "slipping forward" means.

Is this a known issue for speed4j logging? If so, is there a known workaround?

If there are any questions you have of me in regards to this, I'm happy to answer.

Many thanks in advance,
Brian MacDonald
SDET @ Rhapsody International

**Comment by jalkanen** [comment]
The idea is that in order to ensure that we'll only count the objects belonging to the particular time slot, we'll stop the processing when we start seeing StopWatches that belong to the next time slot. It may become a problem under heavy load when the queue fills up faster than we can empty it (which can happen if Thread.sleep() is being slowed down).

Do you possibly have a way to replicate this by the way of an unit test?

(I'm assuming this is all happening on speed4j 0.9 - is that correct?)

**Comment by jalkanen** [comment]
Could you please check out the "issue_7_fix" branch, compile, and rerun your test suite, while keeping jconsole open and send me a screen grab of monitoring of the StopWatchQueueLength attribute?  I have a suspicion that the queue _is_ being emptied regularly, but that you're just having so many operations that the queue just grows very big, and it doesn't have time to empty it all.

**Comment by bmacdonald-rhap** [comment]
Thank you for the quick replies.

We don't have a unit test per se, but we could run this stress test for a shorter amount of time: say 2 hours.

This test ran using speed4j 0.5, not 0.9. I checked the jars on the machine in question, and for the dependencies of hector we specified above in our Maven pom, the Maven install downloaded by default speed4j 0.5 by default. Our pom currently doesn't specify a speed4j dependency.

I should state that while we were using three Cassandra nodes for populating and retrieving, this test ran on a single server, not a farm of servers.  There was an average of 65 threads per second making one Hector call each.

I'll contact the team regarding the time we have to try out your suggestion with the issue_7_fix branch.

Is there an upper limit metric on how many threads/time speed4j is expected to handle?

**Comment by jalkanen** [comment]
The MultiThreadTest runs 100 concurrent threads, each at 100% CPU utilization (so several hundred calls/second), and it seems to all work all right. I think it's more likely due to the large amount of operations involved, since the queue is only emptied at PeriodicalLog intervals (i.e. if you log every 60 seconds, and have 1000 calls/second, you should be expecting about 60,000 objects in the queue, tops). 

What I am worried is that if in your case the PeriodicalLog.collectorThread uses too long to empty the queue, it might start becoming backlogged.

(Note that there is a known memory problem with 0.5, so using 0.9 is a much better idea anyway. The issues_7_fix branch is split from 0.9 codebase.)

**Comment by zznate** [comment]
What about taking out the sleep call and timestamp compare, and just running the thread via ScheduledExecutor#scheduleWithFixedDelay ? I think this would be a cleaner approach and would provide some additional sanity under heavy load.

**Comment by zznate** [comment]
Dropped a PR for this approach: https://github.com/jalkanen/speed4j/pull/8

**Comment by jalkanen** [comment]
I'm not sure whether it's going to solve this particular issue, but I agree that it's a cleaner approach.

**Comment by zznate** [comment]
Well in this case, we could ratchet up the number of executors (currently hard coded to 1) to dedicate more processing resources on the consumption side.

**Comment by jalkanen** [comment]
True, but if there are a lot of calls, there will still be a number of StopWatches in the queue, since it only gets emptied at specified intervals. Another possibility would be to empty the queue as fast as possible, but we need to store the data somewhere to calculate percentiles.

Though I do have a couple of ideas on how to make it use less memory; the CollectedStatistics object is smaller than the StopWatch.

**Comment by zznate** [comment]
As opposed to queuing stopWatch objs, how about applying them to CS immediately and just dumping the CS at the interval? LatencyTracker and EstimatedHistogram in Cassandra sort of work this way.

**Comment by jalkanen** [comment]
Exactly what I was thinking...

----- Reply message -----
Lähettäjä: "zznate" reply@reply.github.com
Vastaanottaja: jalkanen@ecyrd.com
Aihe: [speed4j] Memory Leak in PeriodicalLog's StopWatch queue (PNG links of profiler included) (#7)
Päivämäärä: pe, heinäkuuta 8, 2011 19:05

As opposed to queuing stopWatch objs, how about applying them to CS immediately and just dumping the CS at the interval? LatencyTracker and EstimatedHistogram in Cassandra sort of work this way.

##

**Comment by bluelu** [comment]
Seeing the same issue with 0.9. The leak has grown to about 250MB in one day.

**Comment by bmacdonald-rhap** [comment]
Update: Last friday, we tested the upgrade of speed4j to 0.9 from 0.5. There has been no discernible change in our memory leak issue reported above.  We unfortunately don't have time to compile and test the special branch above, with our schedule.  We will have to mitigate with our release via scheduled restarts until a leak-less version of the entire Hector suite is released.

**Comment by jalkanen** [comment]
I just dropped a possible release candidate in http://www.ecyrd.com/~jalkanen/Speed4j/. This version has much more eager StopWatch processing and also caps the Queue size to prevent runaway threads from generating too many StopWatches.

Please test and see if it works for you (the source code is in issue_7_fix branch).

**Comment by jalkanen** [comment]
0.10 has been released to Maven Central which should fix this issue. I'll keep it open for a while, and if I don't hear any comments, I'll close this issue.

**Comment by bmacdonald-rhap** [comment]
I'm contacting my team right now, asking if there is time in our schedule to upgrade and retest. I'll keep you updated.

**Comment by jalkanen** [comment]
Any news or shall I close this?

**Comment by jalkanen** [comment]
Closing, no further comments received.
